FROM python:3.10
COPY . /advs

WORKDIR /advs

RUN pip install --no-cache-dir -r requirements-dev.txt

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.7.3/wait /wait
RUN chmod +x /wait

ENTRYPOINT /wait && bash ./entrypoint.sh